fabrica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('clientes.urls')),
    path('productos/', include('productos.urls')),
    path('', include('remisiones.urls'))
]

# handler404 = 'remisiones.views.handler_404'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productos/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

app_name = 'productos'
urlpatterns = [
    path('', listar_productos, name='list_productos'),
    path('agregar_producto/', login_required(CrearProducto.as_view()), name='add_producto'),
    path('editar_producto/<int:pk>/', login_required(ActualizarProducto.as_view()), name='edit_producto'),
    path('<int:pk>/', login_required(EliminarProducto.as_view()), name='del_producto'),
    path('stock/', stock_pdf, name='stock'),
    # recepciones
    path('recepciones/', listar_recepciones, name='list_recepciones'),
    path('agregar_recepcion/', agregar_recepcion, name='add_recepcion'),
    path('eliminar_recepcion/<int:pk>/', login_required(EliminarRecepcion.as_view()), name='del_recepcion'),
    path('recepcion/<int:pk>/', recepcionar, name='recepcionar'),
    path('detalle_recepcion/<int:pk>', detalle, name='detail_recepcion'),
    path('pdf_recepciones/recepcion_<int:pk>', export_pdf, name='pdf_recep'),
    # carrito
    path('recepcion/', recepciones, name='recep'),
    path('add_recepcion/<int:producto_id>/', agregar_producto, name='Add'),
    path('del_recepcion/<int:producto_id>/', eliminar_producto, name='Del'),
    path('sub_recepcion/<int:producto_id>/', restar_producto, name='Sub'),
    path('clear_recepcion/', limpiar_carrito, name='CLS'),
    path('guardar_recepcion/', save_recepcion, name='save')
]

remisiones/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

app_name = 'remisiones'
urlpatterns = [
    # login
    path('registro/', registro, name='registro'),
    path('login/', login_page, name='login'),
    path('logout/', logout_user, name='logout'),
    # remisiones
    path('', listar_remisiones, name='list_remisiones'),
    path('agregar_remision/', agregar_remision, name='add_remision'),
    path('eliminar_remision/<int:pk>/', login_required(EliminarResmision.as_view()), name='del_remision'),
    path('<int:pk>/', despachar, name='despachar'),
    path('detalle_remision/<int:pk>', detalle, name='detail_remision'),
    path('pdf_remisiones/factura_<int:pk>', export_pdf, name='pdf_rem'),
    # carrito
    path('carrito/', remisiones, name='rem'),
    path('agregar_carrito/<int:producto_id>/', agregar_producto, name='Add'),
    path('eliminar_carrito/<int:producto_id>/', eliminar_producto, name='Del'),
    path('restar_carrito/<int:producto_id>/', restar_producto, name='Sub'),
    path('limpiar_carrito/', limpiar_carrito, name='CLS'),
    path('guardar_carrito/', save_carrito, name='save')
]

remisiones/models.py
from django.db import models
from clientes.models import Cliente
from datetime import date


class LowerField(models.CharField):

    def get_prep_value(self, value):
        return str(value).lower()


class UpperField(models.CharField):

    def get_prep_value(self, value):
        return str(value).upper()


class Remisiones(models.Model):
    codigo = UpperField(max_length=10, unique=True, null=False, blank=False)
    fecha_despacho = models.DateField(default=date.today(),null=False, blank=False)
    estado = models.BooleanField(default=True)
    orden = models.BooleanField(default=False)
    usuario = LowerField(max_length=15, null=True, default='')
    cliente_id = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.codigo:
            count = Remisiones.objects.all().count()
            if count > 0:
                key = Remisiones.objects.order_by('id').last().id
                new_id = 'D' + str(key+1).zfill(3)
            else:
                new_id = 'D' + str(1).zfill(3)
            self.codigo = new_id
        super(Remisiones, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.codigo

remisiones/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from datetime import date
from django.utils import timezone
from productos.models import RemiProd
from .models import Remisiones


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'is_superuser']

class RemisionForm(forms.ModelForm):
    class Meta:
        model = Remisiones
        fields = ['fecha_despacho', 'cliente_id']
        labels = {
            # 'codigo': 'Código',
            'fecha_despacho': 'Fecha de Despacho',
            'cliente_id': 'ID Cliente',
        }
        widgets = {
            # 'codigo': forms.TextInput(
            #     attrs = {
            #         'class': 'form-control',
            #         'placeholder': ''
            #     }
            # ),
            'fecha_despacho': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'class': 'form-control',
                    'type': 'date',
                    'value': date.today()
                }
            ),
            'cliente_id': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Ingrese el código del Cliente'
                }
            ),
        }
    
    # def clean(self):
    #     try:
    #         sc = Remisiones.objects.get(
    #             cliente_id=self.cleaned_data["cliente_id"]
    #         )
    #         if not sc.exists():
    #             raise forms.ValidationError('Registro no existe')
    #     except Remisiones.DoesNotExist:
    #         pass
    #     return self.cleaned_data


class CarritoForm(forms.ModelForm):
    class Meta:
        model = RemiProd
        fields = ['cantidad', 'remision_id', 'producto_id']


class DespacharForm(forms.ModelForm):
    class Meta:
        model = Remisiones
        fields = ['estado']

remisiones/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import View
from django.http import HttpResponse, JsonResponse
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.contrib import messages
# from django.shortcuts import render_to_response
# from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from productos.models import Producto, RemiProd
from .carrito import Carrito
from .models import Remisiones
from .forms import RemisionForm, CreateUserForm
from .utils import render_to_pdf


# ##### error 404
# def handler_404(request, *args, **kwargs):
#     response = render_to_response(
#         '404.html',
#         {},
#         context_instance=RequestContext(request)
#     )
#     response.status_code = 404
#     return response

############## Login
def registro(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'La cuenta fue creada')
            return redirect('remisiones:login')
    context = {
        'form': form
    }
    return render(request, 'registro.html', context)


def login_page(request):
    if request.user.is_authenticated:
        return redirect('remisiones:list_remisiones')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('remisiones:list_remisiones')
            else:
                messages.info(request, 'Usuario o Contraseña incorrecta')
        context = {}
        return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    return redirect('remisiones:login')


############# remisiones
@login_required(login_url='remisiones:login')
def listar_remisiones(request):
    context = {}
    queryset = request.GET.get('buscar')
    inicio = request.GET.get('inicio')
    final = request.GET.get('final')
    remisiones = Remisiones.objects.all().order_by('-created')
    if queryset:
        remisiones = Remisiones.objects.filter(
            Q(codigo__icontains = queryset)
        ).distinct()
        context['remisiones'] = remisiones
    if inicio and final:
        remisiones = Remisiones.objects.filter(
            Q(fecha_despacho__range = [inicio, final])
        ).distinct()
        context['remisiones'] = remisiones
    paginator = Paginator(remisiones, 10)
    page = request.GET.get('page')
    remisiones = paginator.get_page(page)
    context['remisiones'] = remisiones
    return render(request, 'remisiones/home.html', context)

@login_required(login_url='remisiones:login')
def agregar_remision(request):
    if request.user.is_superuser:
        limpiar_carrito(request)
        context = {}
        form = RemisionForm(request.POST or None)
        if form.errors:
            return render(request, '404.html')
        elif form.is_valid():
            form.save()
            return remisiones(request)
        context['form'] = form
        return render(request, 'remisiones/create.html', context)
    else:
         return redirect('remisiones:login')


class EliminarResmision(DeleteView):
    model = Remisiones
    template_name = 'remisiones/delete.html'
    success_url = reverse_lazy('remisiones:list_remisiones')


@login_required(login_url='remisiones:login')
def despachar(request, pk):
    obj = get_object_or_404(Remisiones, id=pk)
    if obj.orden == False:
        obj.orden = True
        obj.usuario = request.user.username
        obj.save()
    return redirect('remisiones:list_remisiones')

@login_required(login_url='remisiones:login')
def eliminar_remision(request, remision_id):
    if request.user.is_superuser:
        remision = get_object_or_404(Remisiones, id=remision_id)
        if request.method =="POST":
            remision.delete()
            return redirect('remisiones:list_remisiones')
        context = {
            'remision':remision
            }
        return render(request, 'remisiones/delete.html', context)
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def detalle(request, pk):
    remision = Remisiones.objects.get(id=pk)
    detail = RemiProd.objects.filter(remision_id=pk)
    total_c = 0
    for i in detail:
        total_c += i.cantidad
    context = {
        'detalles': detail,
        'remision': remision,
        'total_c': total_c
    }
    return render(request, 'remisiones/detalle.html', context)

def export_pdf(request, pk):
    remision = Remisiones.objects.get(id=pk)
    detail = RemiProd.objects.filter(remision_id=pk)
    total_p = 0
    total_c = 0
    for i in detail:
        total_c += i.cantidad
    context = {
        'detalles': detail,
        'remision': remision,
        'total_c': total_c
    }
    pdf = render_to_pdf('remisiones/exportpdf.html', context)
    return HttpResponse(pdf, content_type='application/pdf')


##################### carrito ######################
@login_required(login_url='remisiones:login')
def remisiones(request):
    if request.user.is_superuser:
        context = {}
        remidion_id = Remisiones.objects.order_by('id').last()
        queryset = request.GET.get('buscar')
        productos = Producto.objects.filter(estado=True)
        if queryset:
            productos = Producto.objects.filter(
                Q(codigo__icontains = queryset) |
                Q(nombre__icontains = queryset) |
                Q(marca__icontains = queryset),
                estado = True
            ).distinct()
            context['productos'] = productos
        paginator = Paginator(productos, 10)
        page = request.GET.get('page')
        productos = paginator.get_page(page)
        context['productos'] = productos
        context['remidion_id'] = remidion_id
        return render(request, 'remisiones.html', context)
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def agregar_producto(request, producto_id):
    if request.user.is_superuser:
        carrito = Carrito(request)
        producto = Producto.objects.get(id=producto_id)
        carrito.agregar(producto)
        return redirect('remisiones:rem')
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def eliminar_producto(request, producto_id):
    if request.user.is_superuser:
        carrito = Carrito(request)
        producto = Producto.objects.get(id=producto_id)
        carrito.eliminar(producto)
        return redirect('remisiones:rem')
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def restar_producto(request, producto_id):
    if request.user.is_superuser:
        carrito = Carrito(request)
        producto = Producto.objects.get(id=producto_id)
        carrito.restar(producto)
        return redirect('remisiones:rem')
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def limpiar_carrito(request):
    if request.user.is_superuser:
        carrito = Carrito(request)
        carrito.limpiar()
        return redirect('remisiones:rem')
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def save_carrito(request):
    if request.user.is_superuser:
        remidion_id = Remisiones.objects.order_by('id').last()
        carrito = request.session.get('carrito').values()
        for i in carrito:
            producto_id = Producto.objects.get(id=i['producto_id'])
            pedido = RemiProd(
                cantidad = int(i['cantidad']),
                remision_id = remidion_id,
                producto_id = producto_id
            )
            pedido.save()
            restar = Producto.objects.get(nombre=producto_id)
            restar.cantidad -= int(i['cantidad'])
            #restar.peso -= float(i['peso'])
            restar.save()
        limpiar_carrito(request)
        return redirect('remisiones:list_remisiones')
    else:
         return redirect('remisiones:login')

remisiones/templates/remisiones/create.html
<div class="modal-dialog modal-lg" role='document'>
    <div class="modal-content">
        <div class="modal-header">
            <h2 class='modal-title'>Agregar Remisión</h2>
            <a href="{% url 'remisiones:list_remisiones' %}" class='btn btn-secondary' data-dismiss='modal' aria-label='Close'>
                <span aria-hidden='ture'>&times;</span>
            </a>
        </div>
        <form action="{% url 'remisiones:add_remision' %}" method='POST' enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal-body">
                {% if error %}
                    <h2>{{ error }}</h2>
                {% else %}
                    {{ form.as_p }}
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-success">Confirmar</button>
                <a href="{% url 'remisiones:list_remisiones' %}" class='btn btn-secondary'>Cancelar</a>
            </div>
            {% endif %}
        </form>
    </div>
</div>

<script>
    /*
    var url = $("form").attr("action");
    var token = jQuery("[name=csrfmiddlewaretoken]").val();

    $(function(){
        $("form").submit(function(e){
            e.preventDefault();
            alert(token);
            var formData = $("form").serializeArray();
            // console.log(formData)
            $.ajax({
                url: url,
                method: "POST",
                headers: {'X-CSRFToken': token},
                data: formData
            })
            .done(function(r, textStatus, xhr){
                if(xhr.status == 200){
                    location.reload(true);
                }
                else{
                    alert("error");
                }
            })
            .fail(function (error){
                alert("error");
            });
        });
    });*/
</script>

remisiones/templates/remisiones/delete.html
<div class="modal-dialog modal-lg" role='document'>
    <div class="modal-content">
        <div class="modal-header">
            <h2 class='modal-title'>Eliminar Remisión</h2>
            <a href="{% url 'remisiones:list_remisiones' %}" class='btn btn-secondary' data-dismiss='modal' aria-label='Close'>
                <span aria-hidden='ture'>&times;</span>
            </a>
        </div>
        <form action="{% url 'remisiones:del_remision' object.id %}" method='POST'>
            {% csrf_token %}
            <div class="modal-body">
                <h2 class="alert alert-warning">¿Desea eliminar la orden de remisión <strong>{{ object.codigo }}</strong>?</h2>
            </div>
            <div class="modal-footer">
                <button type='submit' class='btn btn-success'>Aceptar</button>
                <a href="{% url 'remisiones:list_remisiones' %}" class='btn btn-secondary'>Cancelar</a>
            </div>
        </form>
    </div>
</div>

remisiones/templates/remisiones/detalle.html
{% extends 'layout.html' %}

{% block title %}
    Remisiones
{% endblock title %}

{% block content %}
<div class='container'>
    <div class="row">
        <h2 align='center' class='fw-bold'>Comercializadora L.S. S.A.S.</h2>
        <div class="col-md-12" align='right'>
            <a href="{% url 'remisiones:pdf_rem' remision.id %}" class='btn btn-primary'>Generar PDF</a>
        </div>
    </div>
    <div class="row">
        <h5 class='fw-bold'>Datos de Orden</h5>
        <div class="col-md-4">
            <label for="formFileDisabled" class="form-label">Orden N°: </label>
            <input class="form-control" type="text" id="formFileDisabled" disabled value='{{ remision.codigo }}'>
        </div>
        <div class="col-md-4">
            <label for="formFileDisabled" class="form-label">Fecha Remisión: </label>
            <input class="form-control" type="text" id="formFileDisabled" disabled value='{{ remision.created|date:"M. d, Y" }}'>
        </div>
        <div class="col-md-4">
            <label for="formFileDisabled" class="form-label">Fecha Despacho: </label>
            <input class="form-control" type="text" id="formFileDisabled" disabled value='{{ remision.fecha_despacho }}'>
        </div>
    </div>
    <div class="row">
        <h5 class='fw-bold'>Datos de Cliente</h5>
        <div class="col-md-4">
            <label for="formFileDisabled" class="form-label">Recibe: </label>
            <input class="form-control" type="text" id="formFileDisabled" disabled value='{{ remision.cliente_id.nombre|title }}'>
        </div>
        <div class="col-md-4">
            <label for="formFileDisabled" class="form-label">Domicilio: </label>
            <input class="form-control" type="text" id="formFileDisabled" disabled value='{{ remision.cliente_id.direccion|title }}'>
        </div>
    </div><hr>
    <h3 align='center' class='fw-bold'>Detalle</h3>
    <table class='table table-striped'>
        <th>Código</th>
        <th>Producto</th>
        <th>Marca</th>
        <th>Cantidad</th>
        {% for detalle in detalles %}
        <tr>
            <td>{{ detalle.producto_id.codigo }}</td>
            <td>{{ detalle.producto_id|title }}</td>
            <td>{{ detalle.producto_id.marca|title }}</td>
            <td>{{ detalle.cantidad }}</td>
        </tr>
        {% endfor %}
        <tr>
            <th colspan="3">Total:</th>
            <td class='fw-bold'> {{ total_c }} </td>
        </tr>
    </table>
</div>
{% endblock content %}

remisiones/templates/remisiones/home.html
{% extends 'layout.html' %}

{% block title %}
    Remisiones
{% endblock title %}

{% block nav %}
<ul class="nav nav-tabs justify-content-end">
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="{% url 'remisiones:list_remisiones' %}">Despachos</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'productos:list_recepciones' %}">Recepciones</a>
    </li>
  </ul>
{% endblock nav %}

{% block content %}
    <h2 class='fw-bold'>Órdenes: Despacho</h2><br>
    <div class="container">
        <div class="row">
            <div class='col-md-4'>
                <form action="" method='GET'>
                    <input type="text" class='from-control' placeholder='Código...' name='buscar' value='{{ request.GET.buscar }}'>
                    <button type='submit' class='btn btn-success'>Buscar</button>
                </form>
            </div>
            <div class="col-md-6">
                <form action="" method='GET'>
                    <input type="date" format=('%Y-%m-%d') class='from-control' name='inicio' value='{{ request.GET.inicio }}'> a
                    <input type="date" format=('%Y-%m-%d') class='from-control' name='final' value='{{ request.GET.final }}'>
                    <button type='submit' class='btn btn-success'>Buscar</button>
                </form>
            </div>
            {% if user.is_superuser %}
                <div class="col-md-2 fluid" align='right'>
                    <button onclick="abrir_modal_agregar('{% url 'remisiones:add_remision' %}')" class='btn btn-primary'>
                        Agregar
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                        </svg>
                    </button>
                </div>
            {% endif %}
        </div>
    </div><br>

{% if remisiones %}
    <div class='container'>
        <table class='table table-striped'>
            <th>Código</th>
            <th>Cliente</th>
            <th>Fecha Remisión</th>
            <th>Fecha Despacho</th>
            <th>Orden</th>
            <th>Usuario</th>
            <th>Detalle</th>
            {% if user.is_superuser %}
            <th>Eliminar</th>
            {% else %}
            <th>Despachar</th>
            {% endif %}
            {% for remision in remisiones %}
            <tr>
                <td>{{ remision.codigo }}</td>
                <td>{{ remision.cliente_id|title }}</td>
                <td>{{ remision.created|date:"d F Y" }}</td>
                <td>{{ remision.fecha_despacho|date:"d F Y" }}</td>
                <td>{% if remision.orden == True %}
                        <span class='badge text-bg-success'>Despachado</span>
                    {% else %}
                        <span class='badge text-bg-warning'>Pendiente</span>
                    {% endif %}
                </td>
                <td>{{ remision.usuario|title }}</td>
                <td>
                    <a href="{% url 'remisiones:detail_remision' remision.id %}" class='btn btn-secondary'>
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-file-earmark-text" viewBox="0 0 16 16">
                            <path d="M5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zM5 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5z"/>
                            <path d="M9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.5L9.5 0zm0 1v2A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5z"/>
                          </svg>
                    </a>
                </td>
                <td>
                    {% if user.is_superuser %}
                    <button onclick="abrir_modal_eliminacion('{% url 'remisiones:del_remision' remision.id %}')" class='btn btn-danger'>
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
                            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
                        </svg>
                    </button>
                    {% else %}
                        {% if remision.orden == True %}
                            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-clipboard2-check" viewBox="0 0 16 16">
                                <path d="M9.5 0a.5.5 0 0 1 .5.5.5.5 0 0 0 .5.5.5.5 0 0 1 .5.5V2a.5.5 0 0 1-.5.5h-5A.5.5 0 0 1 5 2v-.5a.5.5 0 0 1 .5-.5.5.5 0 0 0 .5-.5.5.5 0 0 1 .5-.5h3Z"/>
                                <path d="M3 2.5a.5.5 0 0 1 .5-.5H4a.5.5 0 0 0 0-1h-.5A1.5 1.5 0 0 0 2 2.5v12A1.5 1.5 0 0 0 3.5 16h9a1.5 1.5 0 0 0 1.5-1.5v-12A1.5 1.5 0 0 0 12.5 1H12a.5.5 0 0 0 0 1h.5a.5.5 0 0 1 .5.5v12a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5v-12Z"/>
                                <path d="M10.854 7.854a.5.5 0 0 0-.708-.708L7.5 9.793 6.354 8.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3Z"/>
                            </svg>
                            {% else %}
                            <a href="{% url 'remisiones:despachar' remision.id %}" class='btn btn-success'>
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-check-square" viewBox="0 0 16 16">
                                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                                    <path d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.235.235 0 0 1 .02-.022z"/>
                                </svg>
                            </a>
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <div class="row">
        <div class="col-md-12" align='center'>
            <div class="col-md-6" align='left'>
                {% if remisiones.has_previous %}
                    <div class="">
                        <a href="?page=1" class='btn btn-primary'>&laquo;Primera</a>
                        <a href="?page={{ remisiones.previous_page_number }} {% if request.GET.search %}&q={{ request.GET.search }}{% endif %}" class='btn btn-primary'>Anterior</a>
                    </div>
                {% endif %}
            </div>
            <div class="col-md-6" align='right'>
                {% if remisiones.has_next %}
                    <div class="">
                        <a href="?page={{ remisiones.next_page_number }} {% if request.GET.search %}&q={{ request.GET.search }}{% endif %}" class='btn btn-primary'>Siguiente</a>
                        <a href="?page={{ remisiones.paginator.num_pages }}" class='btn btn-primary'>Última&raquo;</a>
                    </div>
                {% endif %}
            </div>
    </div>
{% else %}
    <h3 class='alert alert-info'>No hay órdenes de remisión registradas.</h3>
{% endif %}
    <!-- Modal -->
    <div class="modal fade" id='agregar' role='dialog'>

    </div>

    <div class="modal fade" id='eliminacion', role='dialog'>

    </div>

{% endblock content %}

{% block extrajs %}
    <script type='text/javascript'>
        var $ = jQuery.noConflict();
        
        function abrir_modal_eliminacion(url){
            $('#eliminacion').load(url, function(){
                $(this).modal('show');
            });
        }

        function abrir_modal_agregar(url){
            $('#agregar').load(url, function(){
                $(this).modal('show');
            });
        }
    </script>
{% endblock extrajs %}