fabrica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('clientes.urls')),
    path('productos/', include('productos.urls')),
    path('', include('remisiones.urls'))
]

# handler404 = 'remisiones.views.handler_404'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productos/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

app_name = 'productos'
urlpatterns = [
    path('', listar_productos, name='list_productos'),
    path('agregar_producto/', login_required(CrearProducto.as_view()), name='add_producto'),
    path('editar_producto/<int:pk>/', login_required(ActualizarProducto.as_view()), name='edit_producto'),
    path('<int:pk>/', login_required(EliminarProducto.as_view()), name='del_producto'),
    path('stock/', stock_pdf, name='stock'),
    # recepciones
    path('recepciones/', listar_recepciones, name='list_recepciones'),
    path('agregar_recepcion/', agregar_recepcion, name='add_recepcion'),
    path('eliminar_recepcion/<int:pk>/', login_required(EliminarRecepcion.as_view()), name='del_recepcion'),
    path('recepcion/<int:pk>/', recepcionar, name='recepcionar'),
    path('detalle_recepcion/<int:pk>', detalle, name='detail_recepcion'),
    path('pdf_recepciones/recepcion_<int:pk>', export_pdf, name='pdf_recep'),
    # carrito
    path('recepcion/', recepciones, name='recep'),
    path('add_recepcion/<int:producto_id>/', agregar_producto, name='Add'),
    path('del_recepcion/<int:producto_id>/', eliminar_producto, name='Del'),
    path('sub_recepcion/<int:producto_id>/', restar_producto, name='Sub'),
    path('clear_recepcion/', limpiar_carrito, name='CLS'),
    path('guardar_recepcion/', save_recepcion, name='save')
]

remisiones/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

app_name = 'remisiones'
urlpatterns = [
    # login
    path('registro/', registro, name='registro'),
    path('login/', login_page, name='login'),
    path('logout/', logout_user, name='logout'),
    # remisiones
    path('', listar_remisiones, name='list_remisiones'),
    path('agregar_remision/', agregar_remision, name='add_remision'),
    path('eliminar_remision/<int:pk>/', login_required(EliminarResmision.as_view()), name='del_remision'),
    path('<int:pk>/', despachar, name='despachar'),
    path('detalle_remision/<int:pk>', detalle, name='detail_remision'),
    path('pdf_remisiones/factura_<int:pk>', export_pdf, name='pdf_rem'),
    # carrito
    path('carrito/', remisiones, name='rem'),
    path('agregar_carrito/<int:producto_id>/', agregar_producto, name='Add'),
    path('eliminar_carrito/<int:producto_id>/', eliminar_producto, name='Del'),
    path('restar_carrito/<int:producto_id>/', restar_producto, name='Sub'),
    path('limpiar_carrito/', limpiar_carrito, name='CLS'),
    path('guardar_carrito/', save_carrito, name='save')
]

productos/models.py
from django.db import models
from remisiones.models import Remisiones
from clientes.models import Proveedor
from datetime import date


class LowerField(models.CharField):

    def get_prep_value(self, value):
        return str(value).lower()


class UpperField(models.CharField):

    def get_prep_value(self, value):
        return str(value).upper()


class Producto(models.Model):
    codigo = UpperField(max_length=10, unique=True, null=False, blank=False)
    nombre = LowerField(max_length=150, null=False, blank=False)
    marca = LowerField(max_length=150, null=True, blank=True)
    cantidad = models.IntegerField()
    estado = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre
    

class RemiProd(models.Model):
    cantidad = models.IntegerField()
    remision_id = models.ForeignKey(Remisiones, on_delete=models.CASCADE)
    producto_id = models.ForeignKey(Producto, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)


class Recepcion(models.Model):
    fecha_recepcion = models.DateField(default=date.today(),null=False, blank=False)
    orden = models.BooleanField(default=False)
    usuario = LowerField(max_length=15, null=True, default='')
    proveedor_id = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)


class ReceProd(models.Model):
    cantidad = models.IntegerField()
    producto_id = models.ForeignKey(Producto, on_delete=models.CASCADE)
    recepcion_id = models.ForeignKey(Recepcion, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

productos/forms.py
from django import forms
from .models import Producto, Recepcion
from datetime import date


class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['codigo','nombre', 'marca', 'cantidad']
        labels = {
            'codigo': 'Código',
            'nombre': 'Nombre',
            'marca': 'Marca',
            'cantidad': 'Cantidad',
        }
        widgets = {
            'codigo': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Ingrese el código del producto'
                }
            ),
            'nombre': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Ingrese el nombre del producto'
                }
            ),
            'marca': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Ingrese la marca del producto'
                }
            ),
            'cantidad': forms.NumberInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Ingrese la cantidad del producto'
                }
            ),
        }

class RecepcionForm(forms.ModelForm):
    class Meta:
        model = Recepcion
        fields = ['fecha_recepcion', 'proveedor_id']
        labels = {
            'fecha_recepcion': 'Fecha de Recepción',
            'proveedor_id': 'Código Proveedor',
        }
        widgets = {
            'fecha_recepcion': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'class': 'form-control', 
                    'type': 'date',
                    'value': date.today()
                }
            ),
            'proveedor_id': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Ingrese el código del proveedor'
                }
            ),
        }

productos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db.models import Q
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from .models import Producto, Recepcion, ReceProd
from .forms import ProductoForm, RecepcionForm
from remisiones.carrito import Carrito
from remisiones.utils import render_to_pdf

@login_required(login_url='remisiones:login')
def listar_productos(request):
    if request.user.is_superuser:
        context = {}
        queryset = request.GET.get('buscar')
        productos = Producto.objects.filter(estado=True).order_by('-codigo')
        if queryset:
            productos = Producto.objects.filter(
                Q(codigo__icontains = queryset) |
                Q(nombre__icontains = queryset) |
                Q(marca__icontains = queryset),
                estado = True
            ).distinct()
            context['productos'] = productos
        paginator = Paginator(productos, 10)
        page = request.GET.get('page')
        productos = paginator.get_page(page)
        context['productos'] = productos
        return render(request, 'productos/home.html', context)
    else:
         return redirect('remisiones:login')


class CrearProducto(CreateView):
    model = Producto
    template_name = 'productos/create.html'
    form_class = ProductoForm
    success_url = reverse_lazy('productos:list_productos')


class ActualizarProducto(UpdateView):
    model = Producto
    template_name = 'productos/producto.html'
    form_class = ProductoForm
    success_url = reverse_lazy('productos:list_productos')


class EliminarProducto(DeleteView):
    model = Producto
    template_name = 'productos/delete.html'

    def post(self, request, pk, *args, **kwargs):
        obj = Producto.objects.get(id=pk)
        obj.estado = False
        obj.save()
        return redirect('productos:list_productos')
    

############# Recepcion
@login_required(login_url='remisiones:login')
def listar_recepciones(request):
    context = {}
    inicio = request.GET.get('inicio')
    final = request.GET.get('final')
    recepciones = Recepcion.objects.all().order_by('-fecha_recepcion')
    if inicio and final:
        recepciones = Recepcion.objects.filter(
            Q(fecha_recepcion__range = [inicio, final])
        ).distinct()
        context['recepciones'] = recepciones
    paginator = Paginator(recepciones, 10)
    page = request.GET.get('page')
    recepciones = paginator.get_page(page)
    context['recepciones'] = recepciones
    return render(request, 'recepciones/home.html', context)


@login_required(login_url='remisiones:login')
def agregar_recepcion(request):
    if request.user.is_superuser:
        limpiar_carrito(request)
        context = {}
        form = RecepcionForm(request.POST or None)
        if form.errors:
            return render(request, '404.html')
        if form.is_valid():
            form.save()
            return recepciones(request)
        context['form'] = form
        return render(request, 'recepciones/create.html', context)
    else:
         return redirect('remisiones:login')


class EliminarRecepcion(DeleteView):
    model = Recepcion
    template_name = 'recepciones/delete.html'
    success_url = reverse_lazy('productos:list_recepciones')


@login_required(login_url='remisiones:login')
def detalle(request, pk):
    recepcion = Recepcion.objects.get(id=pk)
    detail = ReceProd.objects.filter(recepcion_id=pk)
    total_c = 0
    for i in detail:
        total_c += i.cantidad
    context = {
        'detalles': detail,
        'recepcion': recepcion,
        'total_c': total_c
    }
    return render(request, 'recepciones/detalle.html', context)


def export_pdf(request, pk):
    recepcion = Recepcion.objects.get(id=pk)
    detail = ReceProd.objects.filter(recepcion_id=pk)
    total_c = 0
    for i in detail:
        total_c += i.cantidad
    context = {
        'detalles': detail,
        'recepcion': recepcion,
        'total_c': total_c
    }
    pdf = render_to_pdf('recepciones/exportpdf.html', context)
    return HttpResponse(pdf, content_type='application/pdf')


def stock_pdf(request):
    productos = Producto.objects.filter(estado=True).order_by('codigo')
    total_c = 0
    total_p = productos.count()
    for i in productos:
        total_c += i.cantidad
    context = {
        'productos': productos,
        'total_c': total_c,
        'total_p': total_p
    }
    pdf = render_to_pdf('productos/stock.html', context)
    return HttpResponse(pdf, content_type='application/pdf')


@login_required(login_url='remisiones:login')
def recepcionar(request, pk):
    obj = get_object_or_404(Recepcion, id=pk)
    if obj.orden == False:
        obj.orden = True
        obj.usuario = request.user.username
        obj.save()
    return redirect('productos:list_recepciones')


##################### carrito ######################
@login_required(login_url='remisiones:login')
def recepciones(request):
    if request.user.is_superuser:
        context = {}
        queryset = request.GET.get('buscar')
        productos = Producto.objects.filter(estado=True)
        if queryset:
            productos = Producto.objects.filter(
                Q(codigo__icontains = queryset) |
                Q(nombre__icontains = queryset) |
                Q(marca__icontains = queryset),
                estado = True
            ).distinct()
            context['productos'] = productos
        paginator = Paginator(productos, 10)
        page = request.GET.get('page')
        productos = paginator.get_page(page)
        context['productos'] = productos
        return render(request, 'recepciones/recepcion.html', context)
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def agregar_producto(request, producto_id):
    if request.user.is_superuser:
        carrito = Carrito(request)
        producto = Producto.objects.get(id=producto_id)
        carrito.agregar(producto)
        return redirect('productos:recep')
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def eliminar_producto(request, producto_id):
    if request.user.is_superuser:
        carrito = Carrito(request)
        producto = Producto.objects.get(id=producto_id)
        carrito.eliminar(producto)
        return redirect('productos:recep')
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def restar_producto(request, producto_id):
    if request.user.is_superuser:
        carrito = Carrito(request)
        producto = Producto.objects.get(id=producto_id)
        carrito.restar(producto)
        return redirect('productos:recep')
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def limpiar_carrito(request):
    if request.user.is_superuser:
        carrito = Carrito(request)
        carrito.limpiar()
        return redirect('productos:recep')
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def save_recepcion(request):
    if request.user.is_superuser:
        recepcion_id = Recepcion.objects.order_by('id').last()
        carrito = request.session.get('carrito').values()
        for i in carrito:
            producto_id = Producto.objects.get(id=i['producto_id'])
            pedido = ReceProd(
                cantidad = int(i['cantidad']),
                recepcion_id = recepcion_id,
                producto_id = producto_id
            )
            pedido.save()
            sumar = Producto.objects.get(nombre=producto_id)
            sumar.cantidad += int(i['cantidad'])
            sumar.save()
        limpiar_carrito(request)
        return redirect('productos:list_recepciones')
    else:
         return redirect('remisiones:login')

productos/templates/recepciones/carrito.html
<div class="alert alert-primary" role="alert">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="row" colspan="4" class="text-center">DETALLE</th>
        </tr>
        <tr>
          <th scope="col">CODIGO</th>
          <th scope="col">NOMBRE</th>
          <th scope="col">CANT</th>
        </tr>
      </thead>
      <tbody>
      {% if request.session.carrito.items %}
      {% for key, value in request.session.carrito.items %}
        <tr>
            <td>{{value.codigo}}</td>
            <td>{{value.nombre|title}}</td>
            <td>
                <a href="{% url 'productos:Sub' value.producto_id %}" class="badge btn btn-dark badge-dark">-</a>
                    {{value.cantidad}}
                    <a href="{% url 'productos:Add' value.producto_id %}" class="badge btn btn-dark badge-dark">+</a>
            </td>
        </tr>
      {% endfor %}
      {% else %}
      <tr>
          <td colspan="4">
              <div class="alert alert-danger text-center"> Sin Productos </div>
          </td>
      </tr>
      {% endif %}
        <tr>
          <th scope="row">Total:</th>
          <td></td>
          <td colspan="3">{{total_carrito}}</td>
        </tr>
      </tbody>
    </table>
    <hr>
    </div>
    <div class="row text-center">
      {% if total_carrito > 0 %}
        <div class="col-6"><a href="{% url 'productos:CLS' %}" class="btn btn-danger">Limpiar</a></div>
        <div class="col-6"><a href="{% url 'productos:save' %}" class="btn btn-success">Guardar</a></div>
      {% endif %}
    </div>

productos/templates/recepciones/create.html
<div class="modal-dialog modal-lg" role='document'>
    <div class="modal-content">
        <div class="modal-header">
            <h2 class='modal-title'>Agregar Recepción</h2>
            <a href="{% url 'productos:list_recepciones' %}" class='btn btn-secondary' data-dismiss='modal' aria-label='Close'>
                <span aria-hidden='ture'>&times;</span>
            </a>
        </div>
        <form action="{% url 'productos:add_recepcion' %}" method='POST' enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal-body">
            {% if error %}
                <h2>{{ error }}</h2>
            {% else %}
                {{ form.as_p }}
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-success">Confirmar</button>
                <a href="{% url 'productos:list_recepciones' %}" class='btn btn-secondary'>Cancelar</a>
            </div>
            {% endif %}
        </form>
    </div>
</div>

productos/templates/recepciones/delete.html
<div class="modal-dialog modal-lg" role='document'>
    <div class="modal-content">
        <div class="modal-header">
            <h2 class='modal-title'>Eliminar Recepción</h2>
            <a href="{% url 'productos:list_recepciones' %}" class='btn btn-secondary' data-dismiss='modal' aria-label='Close'>
                <span aria-hidden='ture'>&times;</span>
            </a>
        </div>
        <form action="{% url 'productos:del_recepcion' object.id %}" method='POST'>
            {% csrf_token %}
            <div class="modal-body">
                <h2 class="alert alert-warning">¿Desea eliminar la orden de recepción?</h2>
            </div>
            <div class="modal-footer">
                <button type='submit' class='btn btn-success'>Aceptar</button>
                <a href="{% url 'productos:list_recepciones' %}" class='btn btn-secondary'>Cancelar</a>
            </div>
        </form>
    </div>
</div>

productos/templates/recepciones/home.html
{% extends 'layout.html' %}

{% block title %}
    Recepciones
{% endblock title %}

{% block nav %}
<ul class="nav nav-tabs justify-content-end">
    <li class="nav-item">
      <a class="nav-link" aria-current="page" href="{% url 'remisiones:list_remisiones' %}">Despachos</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'productos:list_recepciones' %}">Recepciones</a>
    </li>
  </ul>
{% endblock nav %}

{% block content %}
    <h2 class='fw-bold'>Órdenes: Recepción</h2><br>
    <div class="container">
        <div class="row">
            <div class='col-md-8'>
                <form action="" method='GET'>
                    <input type="date" format=('%Y-%m-%d') class='from-control' name='inicio' value='{{ request.GET.inicio }}'> a
                    <input type="date" format=('%Y-%m-%d') class='from-control' name='final' value='{{ request.GET.final }}'>
                    <button type='submit' class='btn btn-success'>Buscar</button>
                </form>
            </div>
            {% if user.is_superuser %}
                <div class="col-md-4 fluid" align='right'>
                    <button onclick="abrir_modal_agregar('{% url 'productos:add_recepcion' %}')" class='btn btn-primary'>
                        Agregar
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                        </svg>
                    </button>
                </div>
            {% endif %}
        </div>
    </div><br>

{% if recepciones %}
    <div class='container'>
        <table class='table table-striped'>
            <th>Proveedor</th>
            <th>Fecha Recepción</th>
            <th>Orden</th>
            <th>Usuario</th>
            <th>Detalle</th>
            {% if user.is_superuser %}
            <th>Eliminar</th>
            {% else %}
            <th>Recibir</th>
            {% endif %}
            {% for recepcion in recepciones %}
            <tr>
                <td>{{ recepcion.proveedor_id|title }}</td>
                <td>{{ recepcion.fecha_recepcion|date:"d F Y" }}</td>
                <td>{% if recepcion.orden == True %}
                    <span class='badge text-bg-success'>Recibido</span>
                {% else %}
                    <span class='badge text-bg-warning'>Pendiente</span>
                {% endif %}
                </td>
                <td>{{ recepcion.usuario|title }}</td>
                <td>
                    <a href="{% url 'productos:detail_recepcion' recepcion.id %}" class='btn btn-secondary'>
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-file-earmark-text" viewBox="0 0 16 16">
                            <path d="M5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zM5 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5z"/>
                            <path d="M9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.5L9.5 0zm0 1v2A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5z"/>
                          </svg>
                    </a>
                </td>
                <td>
                    {% if user.is_superuser %}
                    <button onclick="abrir_modal_eliminacion('{% url 'productos:del_recepcion' recepcion.id %}')" class='btn btn-danger'>
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
                            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
                          </svg>
                    </button>
                    {% else %}
                        {% if recepcion.orden == True %}
                            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-clipboard2-check" viewBox="0 0 16 16">
                                <path d="M9.5 0a.5.5 0 0 1 .5.5.5.5 0 0 0 .5.5.5.5 0 0 1 .5.5V2a.5.5 0 0 1-.5.5h-5A.5.5 0 0 1 5 2v-.5a.5.5 0 0 1 .5-.5.5.5 0 0 0 .5-.5.5.5 0 0 1 .5-.5h3Z"/>
                                <path d="M3 2.5a.5.5 0 0 1 .5-.5H4a.5.5 0 0 0 0-1h-.5A1.5 1.5 0 0 0 2 2.5v12A1.5 1.5 0 0 0 3.5 16h9a1.5 1.5 0 0 0 1.5-1.5v-12A1.5 1.5 0 0 0 12.5 1H12a.5.5 0 0 0 0 1h.5a.5.5 0 0 1 .5.5v12a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5v-12Z"/>
                                <path d="M10.854 7.854a.5.5 0 0 0-.708-.708L7.5 9.793 6.354 8.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3Z"/>
                            </svg>
                            {% else %}
                            <a href="{% url 'productos:recepcionar' recepcion.id %}" class='btn btn-success'>
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-check-square" viewBox="0 0 16 16">
                                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                                    <path d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.235.235 0 0 1 .02-.022z"/>
                                </svg>
                            </a>
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <div class="row">
        <div class="col-md-12" align='center'>
            <div class="col-md-6" align='left'>
                {% if recepciones.has_previous %}
                    <div class="">
                        <a href="?page=1" class='btn btn-primary'>&laquo;Primera</a>
                        <a href="?page={{ recepciones.previous_page_number }} {% if request.GET.search %}&q={{ request.GET.search }}{% endif %}" class='btn btn-primary'>Anterior</a>
                    </div>
                {% endif %}
            </div>
            <div class="col-md-6" align='right'>
                {% if recepciones.has_next %}
                    <div class="">
                        <a href="?page={{ recepciones.next_page_number }} {% if request.GET.search %}&q={{ request.GET.search }}{% endif %}" class='btn btn-primary'>Siguiente</a>
                        <a href="?page={{ recepciones.paginator.num_pages }}" class='btn btn-primary'>Última&raquo;</a>
                    </div>
                {% endif %}
            </div>
    </div>
{% else %}
    <h3 class='alert alert-info'>No hay órdenes de recepción registradas.</h3>
{% endif %}
    <!-- Modal -->
    <div class="modal fade" id='agregar' role='dialog'>

    </div>

    <div class="modal fade" id='edicion' role='dialog'>

    </div>

    <div class="modal fade" id='eliminacion', role='dialog'>

    </div>

{% endblock content %}

{% block extrajs %}
    <script type='text/javascript'>
        var $ = jQuery.noConflict();
        function abrir_modal_edicion(url){
            $('#edicion').load(url, function(){
                $(this).modal('show');
            });
        }

        function abrir_modal_eliminacion(url){
            $('#eliminacion').load(url, function(){
                $(this).modal('show');
            });
        }

        function abrir_modal_agregar(url){
            $('#agregar').load(url, function(){
                $(this).modal('show');
            });
        }
    </script>
{% endblock extrajs %}

productos/templates/recepciones/recepcion.html
{% extends 'layout.html' %}

{% block title %}
    Recepción
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12 align-self-center"><h3 class="fw-bold">Productos</h3></div>
    </div>
    <div class="row">
        <div class='col-md-8'>
            <form action="" method='GET'>
                <div class="col-md-12">
                    <input type="text" class='from-control' placeholder='Buscar...' name='buscar' value='{{ request.GET.buscar }}'>
                    <button type='submit' class='btn btn-success'>Buscar</button>
                </div>
            </form>
        </div>
        <div class="col-6">
            <div class="row" style="padding: 10px 0;">
                <div class="col-12">
                    <div class="row">
                        {% for producto in productos %}
                        <div class="col-4">
                            <div class="card" style="height: 10rem; width: 12rem; margin: 5px 0px;">
                                <div class="card-body">
                                    <h5 class="card-title">{{ producto.nombre|title }}</h5>
                                    <p class="card-text">{{ producto.codigo }}</p>
                                    <a href="{% url 'productos:Add' producto.id %}" class="btn btn-primary">Agregar</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">
            {% include "recepciones/carrito.html" %}
        </div>
    </div>
</div>
{% endblock %}