fabrica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('clientes.urls')),
    path('productos/', include('productos.urls')),
    path('', include('remisiones.urls'))
]

# handler404 = 'remisiones.views.handler_404'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productos/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

app_name = 'productos'
urlpatterns = [
    path('', listar_productos, name='list_productos'),
    path('agregar_producto/', login_required(CrearProducto.as_view()), name='add_producto'),
    path('editar_producto/<int:pk>/', login_required(ActualizarProducto.as_view()), name='edit_producto'),
    path('<int:pk>/', login_required(EliminarProducto.as_view()), name='del_producto'),
    path('stock/', stock_pdf, name='stock'),
    # recepciones
    path('recepciones/', listar_recepciones, name='list_recepciones'),
    path('agregar_recepcion/', agregar_recepcion, name='add_recepcion'),
    path('eliminar_recepcion/<int:pk>/', login_required(EliminarRecepcion.as_view()), name='del_recepcion'),
    path('recepcion/<int:pk>/', recepcionar, name='recepcionar'),
    path('detalle_recepcion/<int:pk>', detalle, name='detail_recepcion'),
    path('pdf_recepciones/recepcion_<int:pk>', export_pdf, name='pdf_recep'),
    # carrito
    path('recepcion/', recepciones, name='recep'),
    path('add_recepcion/<int:producto_id>/', agregar_producto, name='Add'),
    path('del_recepcion/<int:producto_id>/', eliminar_producto, name='Del'),
    path('sub_recepcion/<int:producto_id>/', restar_producto, name='Sub'),
    path('clear_recepcion/', limpiar_carrito, name='CLS'),
    path('guardar_recepcion/', save_recepcion, name='save')
]

productos/models.py
from django.db import models
from remisiones.models import Remisiones
from clientes.models import Proveedor
from datetime import date


class LowerField(models.CharField):

    def get_prep_value(self, value):
        return str(value).lower()


class UpperField(models.CharField):

    def get_prep_value(self, value):
        return str(value).upper()


class Producto(models.Model):
    codigo = UpperField(max_length=10, unique=True, null=False, blank=False)
    nombre = LowerField(max_length=150, null=False, blank=False)
    marca = LowerField(max_length=150, null=True, blank=True)
    cantidad = models.IntegerField()
    estado = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre
    

class RemiProd(models.Model):
    cantidad = models.IntegerField()
    remision_id = models.ForeignKey(Remisiones, on_delete=models.CASCADE)
    producto_id = models.ForeignKey(Producto, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)


class Recepcion(models.Model):
    fecha_recepcion = models.DateField(default=date.today(),null=False, blank=False)
    orden = models.BooleanField(default=False)
    usuario = LowerField(max_length=15, null=True, default='')
    proveedor_id = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)


class ReceProd(models.Model):
    cantidad = models.IntegerField()
    producto_id = models.ForeignKey(Producto, on_delete=models.CASCADE)
    recepcion_id = models.ForeignKey(Recepcion, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

productos/forms.py
from django import forms
from .models import Producto, Recepcion
from datetime import date


class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['codigo','nombre', 'marca', 'cantidad']
        labels = {
            'codigo': 'Código',
            'nombre': 'Nombre',
            'marca': 'Marca',
            'cantidad': 'Cantidad',
        }
        widgets = {
            'codigo': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Ingrese el código del producto'
                }
            ),
            'nombre': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Ingrese el nombre del producto'
                }
            ),
            'marca': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Ingrese la marca del producto'
                }
            ),
            'cantidad': forms.NumberInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Ingrese la cantidad del producto'
                }
            ),
        }

class RecepcionForm(forms.ModelForm):
    class Meta:
        model = Recepcion
        fields = ['fecha_recepcion', 'proveedor_id']
        labels = {
            'fecha_recepcion': 'Fecha de Recepción',
            'proveedor_id': 'Código Proveedor',
        }
        widgets = {
            'fecha_recepcion': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'class': 'form-control', 
                    'type': 'date',
                    'value': date.today()
                }
            ),
            'proveedor_id': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Ingrese el código del proveedor'
                }
            ),
        }

productos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db.models import Q
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from .models import Producto, Recepcion, ReceProd
from .forms import ProductoForm, RecepcionForm
from remisiones.carrito import Carrito
from remisiones.utils import render_to_pdf

@login_required(login_url='remisiones:login')
def listar_productos(request):
    if request.user.is_superuser:
        context = {}
        queryset = request.GET.get('buscar')
        productos = Producto.objects.filter(estado=True).order_by('-codigo')
        if queryset:
            productos = Producto.objects.filter(
                Q(codigo__icontains = queryset) |
                Q(nombre__icontains = queryset) |
                Q(marca__icontains = queryset),
                estado = True
            ).distinct()
            context['productos'] = productos
        paginator = Paginator(productos, 10)
        page = request.GET.get('page')
        productos = paginator.get_page(page)
        context['productos'] = productos
        return render(request, 'productos/home.html', context)
    else:
         return redirect('remisiones:login')


class CrearProducto(CreateView):
    model = Producto
    template_name = 'productos/create.html'
    form_class = ProductoForm
    success_url = reverse_lazy('productos:list_productos')


class ActualizarProducto(UpdateView):
    model = Producto
    template_name = 'productos/producto.html'
    form_class = ProductoForm
    success_url = reverse_lazy('productos:list_productos')


class EliminarProducto(DeleteView):
    model = Producto
    template_name = 'productos/delete.html'

    def post(self, request, pk, *args, **kwargs):
        obj = Producto.objects.get(id=pk)
        obj.estado = False
        obj.save()
        return redirect('productos:list_productos')
    

############# Recepcion
@login_required(login_url='remisiones:login')
def listar_recepciones(request):
    context = {}
    inicio = request.GET.get('inicio')
    final = request.GET.get('final')
    recepciones = Recepcion.objects.all().order_by('-fecha_recepcion')
    if inicio and final:
        recepciones = Recepcion.objects.filter(
            Q(fecha_recepcion__range = [inicio, final])
        ).distinct()
        context['recepciones'] = recepciones
    paginator = Paginator(recepciones, 10)
    page = request.GET.get('page')
    recepciones = paginator.get_page(page)
    context['recepciones'] = recepciones
    return render(request, 'recepciones/home.html', context)


@login_required(login_url='remisiones:login')
def agregar_recepcion(request):
    if request.user.is_superuser:
        limpiar_carrito(request)
        context = {}
        form = RecepcionForm(request.POST or None)
        if form.errors:
            return render(request, '404.html')
        if form.is_valid():
            form.save()
            return recepciones(request)
        context['form'] = form
        return render(request, 'recepciones/create.html', context)
    else:
         return redirect('remisiones:login')


class EliminarRecepcion(DeleteView):
    model = Recepcion
    template_name = 'recepciones/delete.html'
    success_url = reverse_lazy('productos:list_recepciones')


@login_required(login_url='remisiones:login')
def detalle(request, pk):
    recepcion = Recepcion.objects.get(id=pk)
    detail = ReceProd.objects.filter(recepcion_id=pk)
    total_c = 0
    for i in detail:
        total_c += i.cantidad
    context = {
        'detalles': detail,
        'recepcion': recepcion,
        'total_c': total_c
    }
    return render(request, 'recepciones/detalle.html', context)


def export_pdf(request, pk):
    recepcion = Recepcion.objects.get(id=pk)
    detail = ReceProd.objects.filter(recepcion_id=pk)
    total_c = 0
    for i in detail:
        total_c += i.cantidad
    context = {
        'detalles': detail,
        'recepcion': recepcion,
        'total_c': total_c
    }
    pdf = render_to_pdf('recepciones/exportpdf.html', context)
    return HttpResponse(pdf, content_type='application/pdf')


def stock_pdf(request):
    productos = Producto.objects.filter(estado=True).order_by('codigo')
    total_c = 0
    total_p = productos.count()
    for i in productos:
        total_c += i.cantidad
    context = {
        'productos': productos,
        'total_c': total_c,
        'total_p': total_p
    }
    pdf = render_to_pdf('productos/stock.html', context)
    return HttpResponse(pdf, content_type='application/pdf')


@login_required(login_url='remisiones:login')
def recepcionar(request, pk):
    obj = get_object_or_404(Recepcion, id=pk)
    if obj.orden == False:
        obj.orden = True
        obj.usuario = request.user.username
        obj.save()
    return redirect('productos:list_recepciones')


##################### carrito ######################
@login_required(login_url='remisiones:login')
def recepciones(request):
    if request.user.is_superuser:
        context = {}
        queryset = request.GET.get('buscar')
        productos = Producto.objects.filter(estado=True)
        if queryset:
            productos = Producto.objects.filter(
                Q(codigo__icontains = queryset) |
                Q(nombre__icontains = queryset) |
                Q(marca__icontains = queryset),
                estado = True
            ).distinct()
            context['productos'] = productos
        paginator = Paginator(productos, 10)
        page = request.GET.get('page')
        productos = paginator.get_page(page)
        context['productos'] = productos
        return render(request, 'recepciones/recepcion.html', context)
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def agregar_producto(request, producto_id):
    if request.user.is_superuser:
        carrito = Carrito(request)
        producto = Producto.objects.get(id=producto_id)
        carrito.agregar(producto)
        return redirect('productos:recep')
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def eliminar_producto(request, producto_id):
    if request.user.is_superuser:
        carrito = Carrito(request)
        producto = Producto.objects.get(id=producto_id)
        carrito.eliminar(producto)
        return redirect('productos:recep')
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def restar_producto(request, producto_id):
    if request.user.is_superuser:
        carrito = Carrito(request)
        producto = Producto.objects.get(id=producto_id)
        carrito.restar(producto)
        return redirect('productos:recep')
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def limpiar_carrito(request):
    if request.user.is_superuser:
        carrito = Carrito(request)
        carrito.limpiar()
        return redirect('productos:recep')
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def save_recepcion(request):
    if request.user.is_superuser:
        recepcion_id = Recepcion.objects.order_by('id').last()
        carrito = request.session.get('carrito').values()
        for i in carrito:
            producto_id = Producto.objects.get(id=i['producto_id'])
            pedido = ReceProd(
                cantidad = int(i['cantidad']),
                recepcion_id = recepcion_id,
                producto_id = producto_id
            )
            pedido.save()
            sumar = Producto.objects.get(nombre=producto_id)
            sumar.cantidad += int(i['cantidad'])
            sumar.save()
        limpiar_carrito(request)
        return redirect('productos:list_recepciones')
    else:
         return redirect('remisiones:login')

productos/templates/productos/create.html
<div class="modal-dialog modal-lg" role='document'>
    <div class="modal-content">
        <div class="modal-header">
            <h2 class='modal-title'>Agregar Producto</h2>
            <a href="{% url 'productos:list_productos' %}" class='btn btn-secondary' data-dismiss='modal' aria-label='Close'>
                <span aria-hidden='ture'>&times;</span>
            </a>
        </div>
        <form action="{% url 'productos:add_producto' %}" method='POST' enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal-body">
            {% if error %}
                <h2>{{ error }}</h2>
            {% else %}
                {{ form.as_p }}
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-success">Confirmar</button>
                <a href="{% url 'productos:list_productos' %}" class='btn btn-secondary'>Cancelar</a>
            </div>
            {% endif %}
        </form>
    </div>
</div>

productos/templates/productos/delete.html
<div class="modal-dialog modal-lg" role='document'>
    <div class="modal-content">
        <div class="modal-header">
            <h2 class='modal-title'>Eliminar Producto</h2>
            <a href="{% url 'productos:list_productos' %}" class='btn btn-secondary' data-dismiss='modal' aria-label='Close'>
                <span aria-hidden='ture'>&times;</span>
            </a>
        </div>
        <form action="{% url 'productos:del_producto' object.id %}" method='POST'>
            {% csrf_token %}
            <div class="modal-body">
                <h2 class="alert alert-warning">¿Desea eliminar el producto <strong>{{ producto.nombre|title }}</strong>?</h2>
            </div>
            <div class="modal-footer">
                <button type='submit' class='btn btn-success'>Aceptar</button>
                <a href="{% url 'productos:list_productos' %}" class='btn btn-secondary'>Cancelar</a>
            </div>
        </form>
    </div>
</div>

productos/templates/productos/home.html
{% extends 'layout.html' %}

{% block title %}
    Productos
{% endblock title %}

{% block content %}
    <h2 class='fw-bold'>Listado Productos</h2><br>
    <div class="container">
        <div class="row">
            <div class='col-md-6'>
                <form action="" method='GET'>
                    <div class="col-md-12">
                        <input type="text" class='from-control' placeholder='Código, Nombre o Marca' name='buscar' value='{{ request.GET.buscar }}'>
                        <button type='submit' class='btn btn-success'>Buscar</button>
                    </div>
                </form>
            </div>
            <div class="col-md-4 fluid" align='right'>
                <a href="{% url 'productos:stock' %}" class='btn btn-secondary'>
                    Descargar PDF
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-arrow-down" viewBox="0 0 16 16">
                        <path d="M8.5 6.5a.5.5 0 0 0-1 0v3.793L6.354 9.146a.5.5 0 1 0-.708.708l2 2a.5.5 0 0 0 .708 0l2-2a.5.5 0 0 0-.708-.708L8.5 10.293V6.5z"/>
                        <path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5v2z"/>
                    </svg>
                </a>
            </div>
            <div class="col-md-2 fluid" align='right'>
                <button onclick="abrir_modal_agregar('{% url 'productos:add_producto' %}')" class='btn btn-primary'>
                    Agregar
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                    </svg>
                </button>
            </div>
        </div>
    </div><br>

{% if productos %}
    {% comment %} {% for producto in productos %}
    {% if producto.cantidad < 5 %}
        <p class='alert alert-danger col-md-12'>
            <span>El producto <strong>{{ producto.nombre|title }}</strong> se está agotando</span>
            <button onclick='closeCurrentWindow()'>&times;</button>
        </p>
    {% endif %}
    {% endfor %} {% endcomment %}
    <div class='container'>
        <table class='table table-striped'>
            <th>Código</th>
            <th>Nombre</th>
            <th>Marca</th>
            <th>Cantidad</th>
            <th>Editar</th>
            <th>Eliminar</th>
            {% for producto in productos %}
            <tr>
                <td>{{ producto.codigo }}</td>
                <td>{{ producto.nombre|title }}</td>
                <td>{{ producto.marca|title }}</td>
                <td>{{ producto.cantidad }}</td>
                <td>
                    <button onclick="abrir_modal_edicion('{% url 'productos:edit_producto' producto.id %}')" class='btn btn-primary'>
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                        </svg>
                    </button>
                </td>
                <td>
                    <button onclick="abrir_modal_eliminacion('{% url 'productos:del_producto' producto.id %}')" class='btn btn-danger'>
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
                            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
                          </svg>
                        </button>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <div class="row">
        <div class="col-md-12" align='center'>
            <div class="col-md-6" align='left'>
                {% if productos.has_previous %}
                    <div class="">
                        <a href="?page=1" class='btn btn-primary'>&laquo;Primera</a>
                        <a href="?page={{ productos.previous_page_number }} {% if request.GET.search %}&q={{ request.GET.search }}{% endif %}" class='btn btn-primary'>Anterior</a>
                    </div>
                {% endif %}
            </div>
            <div class="col-md-6" align='right'>
                {% if productos.has_next %}
                    <div class="">
                        <a href="?page={{ productos.next_page_number }} {% if request.GET.search %}&q={{ request.GET.search }}{% endif %}" class='btn btn-primary'>Siguiente</a>
                        <a href="?page={{ productos.paginator.num_pages }}" class='btn btn-primary'>Última&raquo;</a>
                    </div>
                {% endif %}
            </div>
    </div>
    
{% else %}
    <h3 class='alert alert-info'>No hay productos registrados.</h3>
{% endif %}
    <!-- Modal -->
    <div class="modal fade" id='agregar' role='dialog'>

    </div>

    <div class="modal fade" id='edicion' role='dialog'>

    </div>

    <div class="modal fade" id='eliminacion', role='dialog'>

    </div>

{% endblock content %}

{% block extrajs %}
    <script type='text/javascript'>
        var $ = jQuery.noConflict();
        function abrir_modal_edicion(url){
            $('#edicion').load(url, function(){
                $(this).modal('show');
            });
        }

        function abrir_modal_eliminacion(url){
            $('#eliminacion').load(url, function(){
                $(this).modal('show');
            });
        }

        function abrir_modal_agregar(url){
            $('#agregar').load(url, function(){
                $(this).modal('show');
            });
        }
        function closeCurrentWindow() {
            window.close();
          }
    </script>
{% endblock extrajs %}

productos/templates/productos/producto.html
<div class="modal-dialog modal-lg" role='document'>
    <div class="modal-content">
        <div class="modal-header">
            <h2 class='modal-title'>Editar Producto</h2>
            <a href="{% url 'productos:list_productos' %}" class='btn btn-secondary' data-dismiss='modal' aria-label='Close'>
                <span aria-hidden='ture'>&times;</span>
            </a>
        </div>
        <form action="{% url 'productos:edit_producto' object.id %}" method='POST'>
            {% csrf_token %}
            <div class="modal-body">
                {{ form.as_p }}
            </div>
            <div class="modal-footer">
                <a href="{% url 'productos:list_productos' %}" class='btn btn-secondary' data-dismiss='modal'>Cancelar</a>
                <button class='btn btn-primary' type='submit'>Confirma</button>
            </div>
        </form>
    </div>
</div>

productos/templates/productos/stock.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta charset="UTF-8">
    <title>Listado Bodega</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="{% static 'img/f1.jpg' %}">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <style>
        * {
            font-size: 10px;
            font-family: 'DejaVu Sans', serif;
        }

        .ticket {
            margin: 2px;
        }

        h1 {
            padding: 0px;
            margin: 0px;
        }

        td,
        th {
            border-top: 1px solid black;
            border-collapse: collapse;
            padding: 2px 0px;
        }

        .centrado {
            text-align: center;
            align-content: center;
        }

        .ticket {
            width: 180px;
            max-width: 180px;
        }

        * {
            margin-top: 0;
            margin-bottom: 0;
            margin-left: 3px;
            margin-right: 0;
            padding: 0;
        }

        .ticket {
            margin: 0;
            padding: 0;
        }

        body {
            text-align: center;
        }

        .span {
            border: double;
            padding: 5px;
        }
    </style>
</head>
<body>
    <div class="">
        <div class="" align="right">	
            <h1 >Comercializadora L.S. S.A.S.</h1>
            <label >Al Mayor y Al Detal</label> <br>
            <em>Orlando Medina - Laura Salcedo</em>
        </div>
    </div>
	<table class="table">
		<h1>Listado de Bodega</h1>
        <p align='left'>
            Total de productos: {{ total_p }}
        </p>
	<thead class="thead-dark">
		<tr>
			<th>Codigo</th>
			<th>Nombre</th>
			<th>Marca</th>
			<th>Cantidad</th>
		</tr>
	</thead>
	<tbody class="text-center">
        {% for producto in productos %}
		<tr>
            <td>{{ producto.codigo }}</td>
			<td>{{ producto.nombre }}</td>
			<td>{{ producto.marca }}</td>
			<td>{{ producto.cantidad }}</td>
		</tr>
        {% endfor %}
	</tbody>
	</table><br>
<footer class="text-center">
	<div class="">	
        <h1 >Comercializadora L.S. S.A.S.</h1>
    </div>
</footer>
</body>
</html>