fabrica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('clientes.urls')),
    path('productos/', include('productos.urls')),
    path('', include('remisiones.urls'))
]

# handler404 = 'remisiones.views.handler_404'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

remisiones/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

app_name = 'remisiones'
urlpatterns = [
    # login
    path('registro/', registro, name='registro'),
    path('login/', login_page, name='login'),
    path('logout/', logout_user, name='logout'),
    # remisiones
    path('', listar_remisiones, name='list_remisiones'),
    path('agregar_remision/', agregar_remision, name='add_remision'),
    path('eliminar_remision/<int:pk>/', login_required(EliminarResmision.as_view()), name='del_remision'),
    path('<int:pk>/', despachar, name='despachar'),
    path('detalle_remision/<int:pk>', detalle, name='detail_remision'),
    path('pdf_remisiones/factura_<int:pk>', export_pdf, name='pdf_rem'),
    # carrito
    path('carrito/', remisiones, name='rem'),
    path('agregar_carrito/<int:producto_id>/', agregar_producto, name='Add'),
    path('eliminar_carrito/<int:producto_id>/', eliminar_producto, name='Del'),
    path('restar_carrito/<int:producto_id>/', restar_producto, name='Sub'),
    path('limpiar_carrito/', limpiar_carrito, name='CLS'),
    path('guardar_carrito/', save_carrito, name='save')
]

remisiones/models.py
from django.db import models
from clientes.models import Cliente
from datetime import date


class LowerField(models.CharField):

    def get_prep_value(self, value):
        return str(value).lower()


class UpperField(models.CharField):

    def get_prep_value(self, value):
        return str(value).upper()


class Remisiones(models.Model):
    codigo = UpperField(max_length=10, unique=True, null=False, blank=False)
    fecha_despacho = models.DateField(default=date.today(),null=False, blank=False)
    estado = models.BooleanField(default=True)
    orden = models.BooleanField(default=False)
    usuario = LowerField(max_length=15, null=True, default='')
    cliente_id = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.codigo:
            count = Remisiones.objects.all().count()
            if count > 0:
                key = Remisiones.objects.order_by('id').last().id
                new_id = 'D' + str(key+1).zfill(3)
            else:
                new_id = 'D' + str(1).zfill(3)
            self.codigo = new_id
        super(Remisiones, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.codigo

remisiones/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from datetime import date
from django.utils import timezone
from productos.models import RemiProd
from .models import Remisiones


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'is_superuser']

class RemisionForm(forms.ModelForm):
    class Meta:
        model = Remisiones
        fields = ['fecha_despacho', 'cliente_id']
        labels = {
            # 'codigo': 'Código',
            'fecha_despacho': 'Fecha de Despacho',
            'cliente_id': 'ID Cliente',
        }
        widgets = {
            # 'codigo': forms.TextInput(
            #     attrs = {
            #         'class': 'form-control',
            #         'placeholder': ''
            #     }
            # ),
            'fecha_despacho': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'class': 'form-control',
                    'type': 'date',
                    'value': date.today()
                }
            ),
            'cliente_id': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Ingrese el código del Cliente'
                }
            ),
        }
    
    # def clean(self):
    #     try:
    #         sc = Remisiones.objects.get(
    #             cliente_id=self.cleaned_data["cliente_id"]
    #         )
    #         if not sc.exists():
    #             raise forms.ValidationError('Registro no existe')
    #     except Remisiones.DoesNotExist:
    #         pass
    #     return self.cleaned_data


class CarritoForm(forms.ModelForm):
    class Meta:
        model = RemiProd
        fields = ['cantidad', 'remision_id', 'producto_id']


class DespacharForm(forms.ModelForm):
    class Meta:
        model = Remisiones
        fields = ['estado']

remisiones/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import View
from django.http import HttpResponse, JsonResponse
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.contrib import messages
# from django.shortcuts import render_to_response
# from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from productos.models import Producto, RemiProd
from .carrito import Carrito
from .models import Remisiones
from .forms import RemisionForm, CreateUserForm
from .utils import render_to_pdf


# ##### error 404
# def handler_404(request, *args, **kwargs):
#     response = render_to_response(
#         '404.html',
#         {},
#         context_instance=RequestContext(request)
#     )
#     response.status_code = 404
#     return response

############## Login
def registro(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'La cuenta fue creada')
            return redirect('remisiones:login')
    context = {
        'form': form
    }
    return render(request, 'registro.html', context)


def login_page(request):
    if request.user.is_authenticated:
        return redirect('remisiones:list_remisiones')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('remisiones:list_remisiones')
            else:
                messages.info(request, 'Usuario o Contraseña incorrecta')
        context = {}
        return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    return redirect('remisiones:login')


############# remisiones
@login_required(login_url='remisiones:login')
def listar_remisiones(request):
    context = {}
    queryset = request.GET.get('buscar')
    inicio = request.GET.get('inicio')
    final = request.GET.get('final')
    remisiones = Remisiones.objects.all().order_by('-created')
    if queryset:
        remisiones = Remisiones.objects.filter(
            Q(codigo__icontains = queryset)
        ).distinct()
        context['remisiones'] = remisiones
    if inicio and final:
        remisiones = Remisiones.objects.filter(
            Q(fecha_despacho__range = [inicio, final])
        ).distinct()
        context['remisiones'] = remisiones
    paginator = Paginator(remisiones, 10)
    page = request.GET.get('page')
    remisiones = paginator.get_page(page)
    context['remisiones'] = remisiones
    return render(request, 'remisiones/home.html', context)

@login_required(login_url='remisiones:login')
def agregar_remision(request):
    if request.user.is_superuser:
        limpiar_carrito(request)
        context = {}
        form = RemisionForm(request.POST or None)
        if form.errors:
            return render(request, '404.html')
        elif form.is_valid():
            form.save()
            return remisiones(request)
        context['form'] = form
        return render(request, 'remisiones/create.html', context)
    else:
         return redirect('remisiones:login')


class EliminarResmision(DeleteView):
    model = Remisiones
    template_name = 'remisiones/delete.html'
    success_url = reverse_lazy('remisiones:list_remisiones')


@login_required(login_url='remisiones:login')
def despachar(request, pk):
    obj = get_object_or_404(Remisiones, id=pk)
    if obj.orden == False:
        obj.orden = True
        obj.usuario = request.user.username
        obj.save()
    return redirect('remisiones:list_remisiones')

@login_required(login_url='remisiones:login')
def eliminar_remision(request, remision_id):
    if request.user.is_superuser:
        remision = get_object_or_404(Remisiones, id=remision_id)
        if request.method =="POST":
            remision.delete()
            return redirect('remisiones:list_remisiones')
        context = {
            'remision':remision
            }
        return render(request, 'remisiones/delete.html', context)
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def detalle(request, pk):
    remision = Remisiones.objects.get(id=pk)
    detail = RemiProd.objects.filter(remision_id=pk)
    total_c = 0
    for i in detail:
        total_c += i.cantidad
    context = {
        'detalles': detail,
        'remision': remision,
        'total_c': total_c
    }
    return render(request, 'remisiones/detalle.html', context)

def export_pdf(request, pk):
    remision = Remisiones.objects.get(id=pk)
    detail = RemiProd.objects.filter(remision_id=pk)
    total_p = 0
    total_c = 0
    for i in detail:
        total_c += i.cantidad
    context = {
        'detalles': detail,
        'remision': remision,
        'total_c': total_c
    }
    pdf = render_to_pdf('remisiones/exportpdf.html', context)
    return HttpResponse(pdf, content_type='application/pdf')


##################### carrito ######################
@login_required(login_url='remisiones:login')
def remisiones(request):
    if request.user.is_superuser:
        context = {}
        remidion_id = Remisiones.objects.order_by('id').last()
        queryset = request.GET.get('buscar')
        productos = Producto.objects.filter(estado=True)
        if queryset:
            productos = Producto.objects.filter(
                Q(codigo__icontains = queryset) |
                Q(nombre__icontains = queryset) |
                Q(marca__icontains = queryset),
                estado = True
            ).distinct()
            context['productos'] = productos
        paginator = Paginator(productos, 10)
        page = request.GET.get('page')
        productos = paginator.get_page(page)
        context['productos'] = productos
        context['remidion_id'] = remidion_id
        return render(request, 'remisiones.html', context)
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def agregar_producto(request, producto_id):
    if request.user.is_superuser:
        carrito = Carrito(request)
        producto = Producto.objects.get(id=producto_id)
        carrito.agregar(producto)
        return redirect('remisiones:rem')
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def eliminar_producto(request, producto_id):
    if request.user.is_superuser:
        carrito = Carrito(request)
        producto = Producto.objects.get(id=producto_id)
        carrito.eliminar(producto)
        return redirect('remisiones:rem')
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def restar_producto(request, producto_id):
    if request.user.is_superuser:
        carrito = Carrito(request)
        producto = Producto.objects.get(id=producto_id)
        carrito.restar(producto)
        return redirect('remisiones:rem')
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def limpiar_carrito(request):
    if request.user.is_superuser:
        carrito = Carrito(request)
        carrito.limpiar()
        return redirect('remisiones:rem')
    else:
         return redirect('remisiones:login')

@login_required(login_url='remisiones:login')
def save_carrito(request):
    if request.user.is_superuser:
        remidion_id = Remisiones.objects.order_by('id').last()
        carrito = request.session.get('carrito').values()
        for i in carrito:
            producto_id = Producto.objects.get(id=i['producto_id'])
            pedido = RemiProd(
                cantidad = int(i['cantidad']),
                remision_id = remidion_id,
                producto_id = producto_id
            )
            pedido.save()
            restar = Producto.objects.get(nombre=producto_id)
            restar.cantidad -= int(i['cantidad'])
            #restar.peso -= float(i['peso'])
            restar.save()
        limpiar_carrito(request)
        return redirect('remisiones:list_remisiones')
    else:
         return redirect('remisiones:login')

remisiones/templates/carrito.html
<div class="alert alert-primary" role="alert">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="row" colspan="4" class="text-center">DETALLE</th>
        </tr>
        <tr>
          <th scope="col">CODIGO</th>
          <th scope="col">NOMBRE</th>
          <th scope="col">CANT</th>
        </tr>
      </thead>
      <tbody>
      {% if request.session.carrito.items %}
      {% for key, value in request.session.carrito.items %}
        <tr>
            <td>{{value.codigo}}</td>
            <td>{{value.nombre|title}}</td>
            <td>
                <a href="{% url 'remisiones:Sub' value.producto_id %}" class="badge btn btn-dark badge-dark">-</a>
                  {{ value.cantidad }} 
                <a href="{% url 'remisiones:Add' value.producto_id %}" class="badge btn btn-dark badge-dark">+</a>
            </td>
        </tr>
      {% endfor %}
      {% else %}
      <tr>
          <td colspan="4">
              <div class="alert alert-danger text-center"> Sin Productos </div>
          </td>
      </tr>
      {% endif %}
        <tr>
          <th scope="row">Total:</th>
          <td></td>
          <td colspan="3">{{total_carrito}}</td>
        </tr>
      </tbody>
    </table>
    <hr>
    </div>
    <div class="row text-center">
      {% if total_carrito > 0 %}
        <div class="col-6"><a href="{% url 'remisiones:CLS' %}" class="btn btn-danger">Limpiar</a></div>
        <div class="col-6"><a href="{% url 'remisiones:save' %}" class="btn btn-success">Guardar</a></div>
      {% endif %}
    </div>

remisiones/templates/remisiones.html
{% extends 'layout.html' %}

{% block title %}
    Remisiones
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12 align-self-center"><h3 class="fw-bold">Productos</h3></div>
        <h3>Orden N°: {{ remision_id }}</h3>
    </div>
    <div class="row">
        <div class='col-md-8'>
            <form action="{% url "remisiones:rem" %}" method='GET'>
                <div class="col-md-12">
                    <input type="text" class='from-control' placeholder='Buscar...' name='buscar' value='{{ request.GET.buscar }}'>
                    <button type='submit' class='btn btn-success'>Buscar</button>
                </div>
            </form>
        </div>
        <div class="col-6">
            <div class="row" style="padding: 10px 0;">
                <div class="col-12">
                    <div class="row">
                        {% for producto in productos %}
                        <div class="col-4">
                            <div class="card" style="height: 10rem; width: 12rem; margin: 5px 0px;">
                                <div class="card-body">
                                    <h5 class="card-title">{{ producto.nombre|title }}</h5>
                                    <p class="card-text">{{ producto.codigo }}</p>
                                    <a href="{% url 'remisiones:Add' producto.id %}" class="btn btn-primary">Agregar</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">
            {% include "carrito.html" %}
        </div>
    </div>
</div>
{% endblock %}